services:
  finbot.webapi:
    image: finbot.webapi
    build:
      context: .
      dockerfile: FinBot.WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__AppDbContext: Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=finbot_db
    ports:
      - "5001:8080"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finbot_db
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d finbot_db" ]
      timeout: 5s
      interval: 5s
      retries: 5
      
volumes:
  postgres_data: